apiVersion: v1
kind: Service
metadata:
  name: gaia-x-server
  annotations:
    YFGaia/gaia-x: backend
    github: "https://github.com/YFGaia/gaia-x.git"
    app.kubernetes.io/version: 0.0.1
  labels:
    app: gaia-x-server
    version: gaia-x-vue3
spec:
  selector:
    app: gaia-x-server
    version: gaia-x-vue3
  ports:
    - port: 8888
      name: http
      targetPort: 8888
  type: ClusterIP
#  type: NodePort
